name: Security Audit

on:
  schedule:
    - cron: '0 0 * * 1' # Weekly
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Audit dependencies
        run: pnpm audit

      - name: Cache audit results
        uses: actions/cache@v3
        with:
          path: |
            node_modules
            .pnpm-store
          key: ${{ runner.os }}-audit-${{ hashFiles('pnpm-lock.yaml') }}
