name: PR Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Set up pnpm global bin directory
      run: pnpm setup
      env:
        SHELL: bash
    
    - name: Install expo-cli globally
      run: pnpm add -g expo-cli

    - name: Run tests
      run: pnpm test
